
import type { LucideIcon } from 'lucide-react';

export const iconList = [
  "Accessibility", "Activity", "AirVent", "Airplay", "AlarmCheck", "AlarmClockOff",
  "AlarmClock", "AlarmMinus", "AlarmPlus", "Album", "AlertCircle", "AlertOctagon",
  "AlertTriangle", "AlignCenterHorizontal", "AlignCenterVertical", "AlignCenter",
  "AlignEndHorizontal", "AlignEndVertical", "AlignHorizontalDistributeCenter",
  "AlignHorizontalDistributeEnd", "AlignHorizontalDistributeStart",
  "AlignHorizontalJustifyCenter", "AlignHorizontalJustifyEnd", "AlignHorizontalJustifyStart",
  "AlignHorizontalSpaceAround", "AlignHorizontalSpaceBetween", "AlignJustify",
  "AlignLeft", "AlignRight", "AlignStartHorizontal", "AlignStartVertical",
  "AlignVerticalDistributeCenter", "AlignVerticalDistributeEnd",
  "AlignVerticalDistributeStart", "AlignVerticalJustifyCenter", "AlignVerticalJustifyEnd",
  "AlignVerticalJustifyStart", "AlignVerticalSpaceAround", "AlignVerticalSpaceBetween",
  "Anchor", "Angry", "Annoyed", "Aperture", "Apple", "ArchiveRestore", "Archive",
  "Armchair", "ArrowBigDownDash", "ArrowBigDown", "ArrowBigLeftDash", "ArrowBigLeft",
  "ArrowBigRightDash", "ArrowBigRight", "ArrowBigUpDash", "ArrowBigUp", "ArrowDownCircle",
  "ArrowDownLeftFromCircle", "ArrowDownLeft", "ArrowDownRightFromCircle", "ArrowDownRight",
  "ArrowDown", "ArrowLeftCircle", "ArrowLeftRight", "ArrowLeft", "ArrowRightCircle",
  "ArrowRight", "ArrowUpCircle", "ArrowUpDown", "ArrowUpLeftFromCircle", "ArrowUpLeft",
  "ArrowUpRightFromCircle", "ArrowUpRight", "ArrowUp", "Asterisk", "AtSign", "Atom",
  "Award", "Axe", "Axis3d", "Baby", "Backpack", "BadgeAlert", "BadgeCheck", "BadgeDollarSign",
  "BadgeHelp", "BadgeInfo", "BadgeMinus", "BadgePercent", "BadgePlus", "BadgeX", "Badge",
  "BaggageClaim", "Banana", "Banknote", "BarChart2", "BarChart3", "BarChart4", "BarChartBig",
  "BarChartHorizontalBig", "BarChartHorizontal", "BarChart", "Baseline", "Bath", "BatteryCharging",
  "BatteryFull", "BatteryLow", "BatteryMedium", "BatteryWarning", "Battery", "Beaker", "BeanOff",
  "Bean", "BedDouble", "BedSingle", "Bed", "Beef", "Beer", "BellMinus", "BellOff", "BellPlus",
  "BellRing", "Bell", "Bike", "Binary", "Bitcoin", "Blinds", "BluetoothConnected", "BluetoothOff",
  "BluetoothSearching", "Bluetooth", "Bold", "Bomb", "Bone", "BookCopy", "BookDown", "BookKey",
  "BookLock", "BookMarked", "BookMinus", "BookOpenCheck", "BookOpen", "BookPlus", "BookTemplate",
  "BookUp", "BookX", "Book", "BookmarkMinus", "BookmarkPlus", "Bookmark", "Bot", "BoxSelect",
  "Box", "Boxes", "BrainCircuit", "BrainCog", "Brain", "Briefcase", "Brush", "Bug", "Building2",
  "Building", "Bus", "Cake", "Calculator", "CalendarCheck2", "CalendarCheck", "CalendarClock",
  "CalendarDays", "CalendarHeart", "CalendarMinus", "CalendarOff", "CalendarPlus", "CalendarRange",
  "CalendarSearch", "CalendarX2", "CalendarX", "Calendar", "CameraOff", "Camera", "CandlestickChart",
  "CandyOff", "Candy", "Car", "Carrot", "CaseLower", "CaseSensitive", "CaseUpper", "Cat",
  "CheckCheck", "CheckCircle2", "CheckCircle", "CheckSquare", "Check", "ChefHat", "Cherry",
  "ChevronDownSquare", "ChevronDown", "ChevronLeftSquare", "ChevronLeft", "ChevronRightSquare",
  "ChevronRight", "ChevronUpSquare", "ChevronUp", "ChevronsDownUp", "ChevronsDown", "ChevronsLeftRight",
  "ChevronsLeft", "ChevronsRightLeft", "ChevronsRight", "ChevronsUpDown", "ChevronsUp", "Chrome",
  "Church", "CigaretteOff", "Cigarette", "CircleDot", "CircleEllipsis", "CircleSlashed", "Circle",
  "Citrus", "Clapperboard", "ClipboardCheck", "ClipboardCopy", "ClipboardEdit", "ClipboardList",
  "ClipboardMinus", "ClipboardPlus", "ClipboardSignature", "ClipboardType", "ClipboardX",
  "Clipboard", "Clock1", "Clock10", "Clock11", "Clock12", "Clock2", "Clock3", "Clock4", "Clock5",
  "Clock6", "Clock7", "Clock8", "Clock9", "Clock", "CloudCog", "CloudDrizzle", "CloudFog",
  "CloudHail", "CloudLightning", "CloudMoonRain", "CloudMoon", "CloudOff", "CloudRainWind",
  "CloudRain", "CloudSnow", "CloudSunRain", "CloudSun", "Cloud", "Cloudy", "Clover", "Code2",
  "Code", "Codepen", "Codesandbox", "Coffee", "Cog", "Coins", "Columns", "Command", "Compass",
  "Component", "ConciergeBell", "Construction", "Contact", "Contrast", "Cookie", "CopySlash",
  "Copy", "Copyleft", "Copyright", "CornerDownLeft", "CornerDownRight", "CornerLeftDown",
  "CornerLeftUp", "CornerRightDown", "CornerRightUp", "CornerUpLeft", "CornerUpRight",
  "Cpu", "CreativeCommons", "CreditCard", "Croissant", "Crop", "Cross", "Crosshair", "Crown",
  "CupSoda", "Currency", "DatabaseBackup", "Database", "Delete", "Diamond", "Dice1", "Dice2",
  "Dice3", "Dice4", "Dice5", "Dice6", "Dices", "Diff", "Disc", "DivideCircle", "DivideSquare",
  "Divide", "DnaOff", "Dna", "Dog", "DollarSign", "DoorClosed", "DoorOpen", "DownloadCloud",
  "Download", "Dribbble", "Droplet", "Droplets", "Drumstick", "Dumbbell", "EarOff", "Ear",
  "Edit2", "Edit3", "Edit", "EggFried", "EggOff", "Egg", "EqualNot", "Equal", "Eraser",
  "Euro", "Expand", "ExternalLink", "EyeOff", "Eye", "Facebook", "Factory", "Fan", "FastForward",
  "Feather", "Figma", "FileArchive", "FileAudio2", "FileAudio", "FileAxis3d", "FileBadge2",
  "FileBadge", "FileBarChart2", "FileBarChart", "FileCheck2", "FileCheck", "FileClock",
  "FileCode", "FileCog2", "FileCog", "FileDiff", "FileDigit", "FileDown", "FileEdit",
  "FileHeart", "FileImage", "FileInput", "FileJson2", "FileJson", "FileKey2", "FileKey",
  "FileLineChart", "FileLock2", "FileLock", "FileMinus2", "FileMinus", "FileOutput",
  "FilePieChart", "FilePlus2", "FilePlus", "FileQuestion", "FileScan", "FileSearch2",
  "FileSearch", "FileSignature", "FileSpreadsheet", "FileSymlink", "FileTerminal", "FileText",
  "FileUp", "FileVideo2", "FileVideo", "FileVolume2", "FileVolume", "FileWarning", "FileX2",
  "FileX", "File", "Files", "Film", "FilterX", "Filter", "Fingerprint", "FishOff", "Fish",
  "FlagOff", "FlagTriangleLeft", "FlagTriangleRight", "Flag", "Flame", "FlashlightOff",
  "Flashlight", "FlaskConicalOff", "FlaskConical", "FlaskRound", "FlipHorizontal2",
  "FlipHorizontal", "FlipVertical2", "FlipVertical", "Flower2", "Flower", "Focus", "FoldHorizontal",
  "FoldVertical", "FolderArchive", "FolderCheck", "FolderClock", "FolderClosed", "FolderCog2",
  "FolderCog", "FolderDown", "FolderEdit", "FolderGit2", "FolderGit", "FolderHeart", "FolderInput",
  "FolderKey", "FolderLock", "FolderMinus", "FolderOpen", "FolderOutput", "FolderPlus",
  "FolderSearch2", "FolderSearch", "FolderSymlink", "FolderSync", "FolderTree", "FolderUp",
  "FolderX", "Folder", "Folders", "Footprints", "Forklift", "FormInput", "Forward", "Frame",
  "Framer", "Frown", "Fuel", "FunctionSquare", "Gamepad2", "Gamepad", "Gauge", "Gavel", "Gem",
  "Ghost", "Gift", "GitBranchPlus", "GitBranch", "GitCommit", "GitCompare", "GitFork",
  "GitMerge", "GitPullRequestClosed", "GitPullRequestDraft", "GitPullRequest", "Github",
  "Gitlab", "GlassWater", "Glasses", "Globe2", "Globe", "Grab", "GraduationCap", "Grape",
  "Grid", "GripHorizontal", "GripVertical", "Grip", "Hammer", "HandMetal", "Hand", "HardDrive",
  "HardHat", "Hash", "Haze", "Heading1", "Heading2", "Heading3", "Heading4", "Heading5", "Heading6",
  "Heading", "Headphones", "HeartCrack", "HeartHandshake", "HeartOff", "HeartPulse", "Heart",
  "HelpCircle", "Hexagon", "Highlighter", "History", "Home", "HopOff", "Hop", "Hotel", "Hourglass",
  "IceCream2", "IceCream", "ImageMinus", "ImageOff", "ImagePlus", "Image", "Import", "Inbox",
  "Indent", "IndianRupee", "Infinity", "Info", "Inspect", "Instagram", "Italic", "IterationCcw",
  "IterationCw", "JapaneseYen", "Joystick", "Key", "Keyboard", "LampCeiling", "LampDesk",
  "LampFloor", "LampWallDown", "LampWallUp", "Lamp", "Landmark", "Languages", "Laptop2", "Laptop",
  "LassoSelect", "Lasso", "Laugh", "Layers", "LayoutDashboard", "LayoutGrid", "LayoutList",
  "LayoutTemplate", "Leaf", "Library", "LifeBuoy", "LightbulbOff", "Lightbulb", "LineChart",
  "Link2Off", "Link2", "Link", "Linkedin", "ListChecks", "ListEnd", "ListFilter", "ListMinus",
  "ListMusic", "ListOrdered", "ListPlus", "ListStart", "ListTree", "ListVideo", "ListX", "List",
  "Loader2", "Loader", "LocateFixed", "LocateOff", "Locate", "Lock", "LogIn", "LogOut", "Lollipop",
  "Luggage", "Magnet", "MailCheck", "MailMinus", "MailOpen", "MailPlus", "MailQuestion",
  "MailSearch", "MailWarning", "MailX", "Mail", "Mailbox", "Mails", "MapPinOff", "MapPin", "Map",
  "Martini", "Maximize2", "Maximize", "Medal", "MegaphoneOff", "Megaphone", "Meh", "Menu",
  "MessageCircle", "MessageSquareDashed", "MessageSquarePlus", "MessageSquare", "MessagesSquare",
  "Mic2", "MicOff", "Mic", "Microwave", "Milestone", "MilkOff", "Milk", "Minimize2", "Minimize",
  "MinusCircle", "MinusSquare", "Minus", "MonitorOff", "MonitorSmartphone", "MonitorSpeaker",
  "Monitor", "Moon", "MoreHorizontal", "MoreVertical", "MountainSnow", "Mountain", "MousePointer2",
  "MousePointerClick", "MousePointer", "Mouse", "Move3d", "MoveDiagonal2", "MoveDiagonal",
  "MoveHorizontal", "MoveVertical", "Move", "Music2", "Music3", "Music4", "Music", "Navigation2Off",
  "Navigation2", "NavigationOff", "Navigation", "Network", "Newspaper", "NutOff", "Nut", "Octagon",
  "Option", "Orbit", "Outdent", "Package2", "PackageCheck", "PackageMinus", "PackageOpen",
  "PackagePlus", "PackageSearch", "PackageX", "Package", "PaintBucket", "Paintbrush2", "Paintbrush",
  "Palette", "Palmtree", "PanelBottomClose", "PanelBottomInactive", "PanelBottomOpen", "PanelBottom",
  "PanelLeftClose", "PanelLeftInactive", "PanelLeftOpen", "PanelLeft", "PanelRightClose",
  "PanelRightInactive", "PanelRightOpen", "PanelRight", "PanelTopClose", "PanelTopInactive",
  "PanelTopOpen", "PanelTop", "Paperclip", "Parentheses", "ParkingCircleOff", "ParkingCircle",
  "ParkingSquareOff", "ParkingSquare", "PartyPopper", "PauseCircle", "PauseOctagon", "Pause",
  "PenTool", "Pencil", "Percent", "PersonStanding", "PhoneCall", "PhoneForwarded", "PhoneIncoming",
  "PhoneMissed", "PhoneOff", "PhoneOutgoing", "Phone", "PictureInPicture2", "PictureInPicture",
  "PieChart", "PiggyBank", "PinOff", "Pin", "Pipette", "Pizza", "PlaneLanding", "PlaneTakeoff",
  "Plane", "PlayCircle", "Play", "Plug2", "PlugZap", "Plug", "PlusCircle", "PlusSquare", "Plus",
  "Pocket", "Podcast", "Pointer", "PoundSterling", "PowerOff", "Power", "Printer", "Puzzle",
  "QrCode", "Quote", "RadioReceiver", "RadioTower", "Radio", "Rat", "Receipt", "RectangleHorizontal",
  "RectangleVertical", "Recycle", "Redo2", "Redo", "RefreshCcw", "RefreshCw", "Refrigerator",
  "Regex", "RemoveFormatting", "Repeat1", "Repeat", "ReplaceAll", "Replace", "ReplyAll", "Reply",
  "Rewind", "Rocket", "RockingChair", "Rotate3d", "RotateCcw", "RotateCw", "Router", "Rows",
  "Rss", "Ruler", "RussianRuble", "Sailboat", "Salad", "Sandwich", "SatelliteDish", "Satellite",
  "SaveAll", "Save", "Scale3d", "Scale", "Scaling", "ScanFace", "ScanLine", "Scan", "Scissors",
  "ScreenShareOff", "ScreenShare", "Scroll", "Search", "Send", "SeparatorHorizontal",
  "SeparatorVertical", "ServerCog", "ServerCrash", "ServerOff", "Server", "Settings2", "Settings",
  "Share2", "Share", "Sheet", "ShieldAlert", "ShieldCheck", "ShieldClose", "ShieldOff",
  "ShieldQuestion", "Shield", "Ship", "Shirt", "ShoppingBag", "ShoppingBasket", "ShoppingCart",
  "Shovel", "ShowerHead", "Shrink", "Shrub", "Shuffle", "SidebarClose", "SidebarOpen", "Sidebar",
  "Sigma", "SignalHigh", "SignalLow", "SignalMedium", "SignalZero", "Signal", "Siren", "SkipBack",
  "SkipForward", "Skull", "Slack", "Slice", "SlidersHorizontal", "Sliders", "SmartphoneCharging",
  "Smartphone", "SmilePlus", "Smile", "Snowflake", "Sofa", "Soup", "Space", "Speaker", "Sprout",
  "Square", "StarHalf", "StarOff", "Star", "StepBack", "StepForward", "Stethoscope", "Sticker",
  "StickyNote", "StopCircle", "Store", "StretchHorizontal", "StretchVertical", "Strikethrough",
  "Subscript", "Subtitles", "SunDim", "SunMedium", "SunMoon", "SunOff", "SunSnow", "Sun",
  "Sunrise", "Sunset", "Superscript", "SwissFranc", "SwitchCamera", "Sword", "Swords", "Syringe",
  "Table2", "Table", "Tablet", "Tablets", "Tag", "Tags", "Target", "Tent", "TerminalSquare",
  "Terminal", "TextCursorInput", "TextCursor", "TextSelect", "Text", "ThermometerSnowflake",
  "ThermometerSun", "Thermometer", "ThumbsDown", "ThumbsUp", "Ticket", "TimerOff", "TimerReset",
  "Timer", "ToggleLeft", "ToggleRight", "Tornado", "TouchpadOff", "Touchpad", "TowerControl",
  "ToyBrick", "Train", "Trash2", "Trash", "TreeDeciduous", "TreePine", "Trees", "Trello",
  "TrendingDown", "TrendingUp", "Triangle", "Trophy", "Truck", "Tv2", "Tv", "Twitch", "Twitter",
  "Type", "Umbrella", "Underline", "Undo2", "Undo", "UnfoldHorizontal", "UnfoldVertical",
  "Unlink2", "Unlink", "Unlock", "UploadCloud", "Upload", "Usb", "User2", "UserCheck", "UserCog",
  "UserMinus", "UserPlus", "UserX", "User", "Users2", "Users", "UtensilsCrossed", "Utensils",
  "UtilityPole", "Variable", "Verified", "VibrateOff", "Vibrate", "VideoOff", "Video", "View",
  "Voicemail", "Volume1", "Volume2", "VolumeX", "Volume", "Vote", "Wallet", "Wallpaper", "Wand2",
  "Wand", "Warehouse", "Watch", "Waves", "Webcam", "Webhook", "WheatOff", "Wheat", "WifiOff",
  "Wifi", "Wind", "WineOff", "Wine", "Workflow", "WrapText", "Wrench", "XCircle", "XOctagon",
  "XSquare", "X", "Youtube", "ZapOff", "Zap", "ZoomIn", "ZoomOut"
] as const;

export type IconName = typeof iconList[number];

    